### PR TITLE
docs: Richb edits on shaper_bufferbloat.rst

### PR DESCRIPTION
**Pull request by richb-hanover**
Hi Michal,

This has been a lot of fun. Thanks for the opportunity to edit this document. I hope my changes are useful. Here's what I have done:

- Put all the background info for FQ_Codel at the top

- I made all the lines short. I find it easier to edit, and it's easier to see the changes. (Not so much this time, but in the future. It avoids 200-character lines in a diff where phrases are added and deleted, and you're trying to figure out which words changed...)

- I moved the details of fq_codel out of the tables to the top. Now the tables only contain the critical info about the particular setting (not the entire algorithm)

- In each of the "B" steps, I just said, "Do it like the 'A' step, but use these values." I think it decreases clutter and shows how the A & B steps are similar. It also avoids repetitive instructions that drift apart in subsequent edits. DRY - Don't Repeat Yourself.

- I dropped many of the details of FQ_CoDel machinery (new queues/old queues) since they don't change the settings people need to consider. (Of if they really want to get into it, they should work with the RFC)

- Made capitalization of "FQ_CoDel" consistent with RFC 8290

- Added screenshots of the "big three" useful speed test websites

- I moved a lot of stuff (the "B" tables, for example) to the end of the document so I didn't lose any of that info. I think that material is now redundant - feel free to delete in your final edits.

- I have never used the OPNsense configuration tools, so I don't know exactly how they appear. Please forgive me if I've changed the details - it was not my intent.

Fussy questions:

- Does "queue" parameter need to be set to 2 in theDownload Pipe?

- I don't understand the following, so didn't change the wording. You should check...
	- description of the Download/Upload Queue "mask" parameter
	- description of interface2 in Download Rule

- I did not get much into the text of the "Final FQ_CoDel Tuning" section - I don't really understand all those details (Or I think of them differently). But I always use the defaults and am very happy.

Thanks again!

### CODE REVIEW

**Comment by richb-hanover** [comment]
@SeimusS I forgot to tag your name in the commit message. Let me know if you have questions. Thanks

**Comment by SeimusS** [comment]
@richb-hanover 

Hey Rich many thanks having a look into this and highlighting the points and what you adjusted.

In regards your questions >

> Fussy questions:
> 
>     * Does "queue" parameter need to be set to 2 in theDownload Pipe?

The queue parameter is not needed there, I actually removed it in previous commit.

>     * I don't understand the following, so didn't change the wording. You should check...
>       
>       * description of the Download/Upload Queue "mask" parameter
>       * description of interface2 in Download Rule

MASK is as well not needed, I actually removed it in previous commit.

>     * I did not get much into the text of the "Final FQ_CoDel Tuning" section - I don't really understand all those details (Or I think of them differently). But I always use the defaults and am very happy.

To this I can only agree, the default parameters should work. However there are certain edge cases where a "tuning" is optional. The Tuning section is made by me testing FQ_Codel directly on my ISP circuit and using best practices either from the RFC or bufferbloat.net webside. Its true users shouldnt deal with this. But as I have seen they are touching this, which often results into conflicts that its worse than it was... So I tried to provide some educative way to tell them what to do and expect.


Also I do not know why but you forked my repo from and Older commit, I did last adjustment Jun 12 commit a87a05d8769e710368782fb2d3fe45db68cdadc1 which is in the SeimusS:SeimusS-patch-1. Looks like you did fork the master branch. Sorry for this I probably messed it a bit.

I will go thru your changes and have deeper look. But what you changed from a very quick look gives sense to me.

Regards,
S. (Michal)

**Comment by SeimusS** [comment]
@richb-hanover once again many thanks, I went thru it and I must say its now better than my caffeine stimulated brain could think of.

I am glad you had fun ;)

> This has been a lot of fun. Thanks for the opportunity to edit this document. I hope my changes are useful. Here's what I have done:
> 
>     * Put all the background info for FQ_Codel at the top
I totally agree this looks much more better. The description how FQ_CoDel is working was precisely what I was looking for but I was unable to explain it in a way, you description is perfect.

>     * I made all the lines short. I find it easier to edit, and it's easier to see the changes. (Not so much this time, but in the future. It avoids 200-character lines in a diff where phrases are added and deleted, and you're trying to figure out which words changed...)
I agree, I didn't think of this actually.


>     * I moved the details of fq_codel out of the tables to the top. Now the tables only contain the critical info about the particular setting (not the entire algorithm)
I agree, looks much more better and more cleaner now.


>     * In each of the "B" steps, I just said, "Do it like the 'A' step, but use these values." I think it decreases clutter and shows how the A & B steps are similar. It also avoids repetitive instructions that drift apart in subsequent edits. DRY - Don't Repeat Yourself.
I agree, looks cleaner decreases clutter that was there.

>     * I dropped many of the details of FQ_CoDel machinery (new queues/old queues) since they don't change the settings people need to consider. (Of if they really want to get into it, they should work with the RFC)
I agree.

>     * Made capitalization of "FQ_CoDel" consistent with RFC 8290
To be honest I thought its capital L on the end.

>     * Added screenshots of the "big three" useful speed test websites
This was something I wanted to do at the end but you were faster, Many thanks!

>     * I moved a lot of stuff (the "B" tables, for example) to the end of the document so I didn't lose any of that info. I think that material is now redundant - feel free to delete in your final edits.
I agree. Thank you for letting there for review purposes, after de-clutter the docs its not needed.

>     * I have never used the OPNsense configuration tools, so I don't know exactly how they appear. Please forgive me if I've changed the details - it was not my intent.
No worries about this. I will adjust it if there are some mistakes.

 
> 
> Fussy questions:
> 
>     * Does "queue" parameter need to be set to 2 in theDownload Pipe?
> 
>     * I don't understand the following, so didn't change the wording. You should check...
>       
>       * description of the Download/Upload Queue "mask" parameter
>       * description of interface2 in Download Rule
> 
>     * I did not get much into the text of the "Final FQ_CoDel Tuning" section - I don't really understand all those details (Or I think of them differently). But I always use the defaults and am very happy.
As mentioned queue parameter in Pipe and MASK parameter in Queue will be removed. That was an config oversight from my end.

Overall I like very much the way you did correct the docs. Much more pleasant to read and from point of FQ_Codel much more correct and precise :)


Regards,
S. (Michal)

**Comment by richb-hanover** [comment]
I was happy to do it. I'm done - I have said 99.99% of everything I know :-) so I turn the description back over to you for final touches.

Best regards - Rich

**Comment by SeimusS** [comment]
You know a lot about this <3, and I am happy that Dave did connect us together.

I will quote him "This looks very sane". 

Regards,
S. (Michal)

**Pull request merged**
